"""
Static build database sourced from prydwen.gg.
Used by /build command. Update this file as the meta shifts.
"""

ALL_RESONATORS = [
    "Aalto", "Aemeath", "Augusta", "Baizhi", "Brant", "Buling",
    "Calcharo", "Camellya", "Cantarella", "Carlotta", "Cartethyia",
    "Changli", "Chisa", "Chixia", "Ciaccona", "Danjin", "Denia",
    "Encore", "Galbrena", "Hiyuki", "Iuno", "Jianxin", "Jinhsi", "Jiyan",
    "Lingyang", "Lucilla", "Lucy", "Lumi", "Lupa", "Luuk Herssen",
    "Lynae", "Mornye", "Mortefi", "Phoebe", "Phrolova", "Qiuyuan",
    "Rebecca", "Roccia", "Rover (Aero)", "Rover (Havoc)", "Rover (Spectro)",
    "Sanhua", "Sigrika", "Taoqi", "The Shorekeeper", "Verina",
    "Xiangli Yao", "Yangyang", "Yinlin", "Youhu", "Yuanwu", "Zani", "Zhezhi",
]

# slug used in prydwen URLs (lowercase, spaces→hyphens, parens stripped)
def prydwen_slug(name: str) -> str:
    import re
    s = name.lower()
    s = re.sub(r"[()]+", "", s)
    s = re.sub(r"\s+", "-", s.strip())
    s = re.sub(r"-+", "-", s)
    return s


def prydwen_url(name: str) -> str:
    return f"https://www.prydwen.gg/wuthering-waves/characters/{prydwen_slug(name)}"


# Build data: echo_sets, main_stats per slot, priority substats, notes
# Source: prydwen.gg — June 2026
BUILDS: dict[str, dict] = {
    "Jiyan": {
        "role": "Main DPS",
        "element": "Aero",
        "weapon": "Verdant Summit",
        "echo_sets": ["Sierra Gale (5pc)", "Sierra Gale (4pc) + Void Thunder (1pc)"],
        "echo_mains": {
            "4-cost": "Aero DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "Aero DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Aim for 70%+ Crit Rate. Stack Energy Regen to enable ult rotation.",
        "patch": "3.2",
    },
    "Carlotta": {
        "role": "Main DPS",
        "element": "Glacio",
        "weapon": "The Last Dance",
        "echo_sets": ["Frosty Resolve (5pc)", "Freezing Frost (5pc)"],
        "echo_mains": {
            "4-cost": "Glacio DMG%",
            "3-cost": "CRIT Rate",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT DMG", "CRIT Rate", "ATK%", "Energy Regen"],
        "notes": "Resonance Skill Glacio DPS. Main echo Sentry Construct (Frosty Resolve). Prioritise CRIT DMG after ~70% Crit Rate.",
        "patch": "2.0",
    },
    "Changli": {
        "role": "Main DPS / Flex",
        "element": "Fusion",
        "weapon": "Blazing Brilliance",
        "echo_sets": ["Molten Rift (5pc)"],
        "echo_mains": {
            "4-cost": "Fusion DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "High energy cost — prioritise Energy Regen as secondary substat.",
        "patch": "1.3",
    },
    "Camellya": {
        "role": "Main DPS",
        "element": "Havoc",
        "weapon": "Red Spring",
        "echo_sets": ["Sun-sinking Eclipse (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Havoc DMG%",
            "3-cost-alt": "Havoc DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Basic-attack Havoc DPS (~80% of damage is Basic Attack). Main echo Dreamless (Crownless for a higher ceiling). Somnoire Anchor is the F2P weapon.",
        "patch": "2.0",
    },
    "Jinhsi": {
        "role": "Main DPS",
        "element": "Spectro",
        "weapon": "Ages of Harvest",
        "echo_sets": ["Celestial Light (5pc)"],
        "echo_mains": {
            "4-cost": "Spectro DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT DMG", "CRIT Rate", "ATK%", "Energy Regen"],
        "notes": "Stack Incandescence before using ult for maximum damage.",
        "patch": "1.3",
    },
    "Xiangli Yao": {
        "role": "Main DPS",
        "element": "Electro",
        "weapon": "Verity's Handle",
        "echo_sets": ["Void Thunder (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Electro DMG%",
            "3-cost-alt": "Electro DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Resonance Liberation Electro DPS. Main echo Thundering Mephis. Stack Energy Regen for ult uptime. BiS partner: Yinlin.",
        "patch": "1.2",
    },
    "Phoebe": {
        "role": "Main DPS",
        "element": "Spectro",
        "weapon": "Luminous Hymn",
        "echo_sets": ["Eternal Radiance (5pc)"],
        "echo_mains": {
            "4-cost": "Spectro DMG%",
            "3-cost": "Spectro DMG%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Spectro Frazzle DPS. Main echo Capitaneus (Nightmare: Mourning Aix alt). Moonlit Clouds when played as a sub-DPS.",
        "patch": "2.2",
    },
    "Cantarella": {
        "role": "Sub-DPS / Support",
        "element": "Havoc",
        "weapon": "Whispers of Sirens",
        "echo_sets": ["Midnight Veil (5pc)"],
        "echo_mains": {
            "4-cost": "Havoc DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Havoc Echo-Skill sub-DPS/healer. Main echo Lorelei. Cosmic Ripples / Rime-Draped Sprouts are alt weapons. Pairs with Phrolova.",
        "patch": "2.2",
    },
    "Calcharo": {
        "role": "Main DPS",
        "element": "Electro",
        "weapon": "Lustrous Razor",
        "echo_sets": ["Void Thunder (5pc)"],
        "echo_mains": {
            "4-cost": "Electro DMG%",
            "3-cost": "CRIT Rate",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT DMG", "CRIT Rate", "ATK%", "Energy Regen"],
        "notes": "Strong burst window; save ult for max stack usage.",
        "patch": "1.0",
    },
    "Encore": {
        "role": "Main DPS",
        "element": "Fusion",
        "weapon": "Stringmaster",
        "echo_sets": ["Molten Rift (5pc)"],
        "echo_mains": {
            "4-cost": "Fusion DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Fusion DPS. Main echo Inferno Rider. Stringmaster BiS; Cosmic Ripples is a strong alt. Weave skills for Molten Rift uptime.",
        "patch": "1.0",
    },
    "Danjin": {
        "role": "Main DPS",
        "element": "Havoc",
        "weapon": "Blazing Brilliance",
        "echo_sets": ["Sun-sinking Eclipse (5pc)"],
        "echo_mains": {
            "4-cost": "Havoc DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Flat ATK"],
        "notes": "Havoc burst DPS. Main echo Crownless. Blazing Brilliance has ~100% uptime on her; Red Spring / Emerald of Genesis are alts.",
        "patch": "1.0",
    },
    "Lingyang": {
        "role": "Main DPS",
        "element": "Glacio",
        "weapon": "Abyss Surges",
        "echo_sets": ["Freezing Frost (5pc)"],
        "echo_mains": {
            "4-cost": "Glacio DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Airborne DPS — use ult then launch combos mid-air.",
        "patch": "1.0",
    },
    "Sanhua": {
        "role": "Sub-DPS / Support",
        "element": "Glacio",
        "weapon": "Emerald of Genesis",
        "echo_sets": ["Moonlit Clouds (5pc) — buffer", "Freezing Frost (5pc) — damage"],
        "echo_mains": {
            "4-cost": "Glacio DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Basic-Attack buffer / sub-DPS. Main echo Impermanence Heron (Moonlit Clouds). Overture is a strong alt weapon for faster Outro.",
        "patch": "1.0",
    },
    "Mortefi": {
        "role": "Sub-DPS / Support",
        "element": "Fusion",
        "weapon": "Static Mist",
        "echo_sets": ["Moonlit Clouds (5pc)", "Empyrean Anthem (5pc)"],
        "echo_mains": {
            "4-cost": "Fusion DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Heavy-Attack amplifier support. Main echo Impermanence Heron. Cadenza / Relativistic Jet are 4★ alt weapons.",
        "patch": "1.0",
    },
    "Verina": {
        "role": "Support / Healer",
        "element": "Spectro",
        "weapon": "Stellar Symphony",
        "echo_sets": ["Rejuvenating Glow (5pc)"],
        "echo_mains": {
            "4-cost": "Healing Bonus%",
            "3-cost": "HP%",
            "3-cost-alt": "ATK%",
            "1-cost": "HP%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["Energy Regen", "HP%", "ATK%", "CRIT Rate"],
        "notes": "Universal buffer/healer; ult gives team-wide DMG bonus. Main echo Bell-Borne Geochelone. Variation is the top budget/F2P weapon.",
        "patch": "1.0",
    },
    "The Shorekeeper": {
        "role": "Support / Healer",
        "element": "Spectro",
        "weapon": "Stellar Symphony",
        "echo_sets": ["Rejuvenating Glow (5pc)"],
        "echo_mains": {
            "4-cost": "Healing Bonus%",
            "3-cost": "HP%",
            "3-cost-alt": "Energy Regen",
            "1-cost": "HP%",
            "1-cost-2": "HP%",
        },
        "substats": ["Energy Regen", "HP%", "ATK%", "CRIT Rate"],
        "notes": "Top-tier healer/buffer. Main echo Fallacy of No Return. Stack Energy Regen toward ~250% for the Stellarealm crit buff. Variation is the budget weapon.",
        "patch": "1.3",
    },
    "Baizhi": {
        "role": "Support / Healer",
        "element": "Glacio",
        "weapon": "Stellar Symphony",
        "echo_sets": ["Rejuvenating Glow (5pc)"],
        "echo_mains": {
            "4-cost": "Healing Bonus%",
            "3-cost": "HP%",
            "3-cost-alt": "Energy Regen",
            "1-cost": "HP%",
            "1-cost-2": "HP%",
        },
        "substats": ["Energy Regen", "HP%", "ATK%", "CRIT Rate"],
        "notes": "F2P-friendly healer. Main echo Bell-Borne Geochelone. ER ~100–110%. Variation is the craftable budget weapon.",
        "patch": "1.0",
    },
    "Rover (Havoc)": {
        "role": "Main DPS",
        "element": "Havoc",
        "weapon": "Emerald of Genesis",
        "echo_sets": ["Sun-sinking Eclipse (5pc)"],
        "echo_mains": {
            "4-cost": "Havoc DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Strong free unit. Forte circuit charges quickly in combat.",
        "patch": "1.1",
    },
    "Rover (Spectro)": {
        "role": "Sub-DPS / Support",
        "element": "Spectro",
        "weapon": "Emerald of Genesis",
        "echo_sets": ["Moonlit Clouds (5pc) — sub-DPS buffer", "Eternal Radiance (5pc) — DPS"],
        "echo_mains": {
            "4-cost": "Spectro DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Spectro Frazzle sub-DPS. Moonlit Clouds (buffer) or Eternal Radiance (damage). Main echo Impermanence Heron. ER-hungry; Blazing Brilliance for the damage build.",
        "patch": "1.0",
    },
    "Roccia": {
        "role": "Sub-DPS / Support",
        "element": "Havoc",
        "weapon": "Tragicomedy",
        "echo_sets": ["Midnight Veil (5pc)", "Moonlit Clouds (5pc) — buffer"],
        "echo_mains": {
            "4-cost": "Havoc DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Havoc sub-DPS/buffer. Main echo Nightmare: Impermanence Heron (Midnight Veil) or Impermanence Heron (Moonlit Clouds). Abyss Surges is an alt weapon.",
        "patch": "2.0",
    },
    "Brant": {
        "role": "Main DPS",
        "element": "Fusion",
        "weapon": "Unflickering Valor",
        "echo_sets": ["Tidebreaking Courage (5pc) — needs ~250% ER", "Molten Rift (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Energy Regen",
            "3-cost-alt": "Fusion DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "Energy Regen", "ATK%"],
        "notes": "Basic-attack Fusion DPS with heal/shield utility. Tidebreaking Courage needs ~250% Energy Regen; Molten Rift is the lower-investment alt. Priority: Crit > ER > Basic Attack DMG.",
        "patch": "2.1",
    },
    "Zani": {
        "role": "Main DPS",
        "element": "Spectro",
        "weapon": "Blazing Justice",
        "echo_sets": ["Eternal Radiance (5pc)", "Celestial Light (5pc)"],
        "echo_mains": {
            "4-cost": "Spectro DMG%",
            "3-cost": "Spectro DMG%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Spectro Frazzle DPS. Main echo Capitaneus (3-cost). Keep Energy Regen ~130%.",
        "patch": "2.4",
    },
    "Aalto": {
        "role": "Sub-DPS / Support",
        "element": "Aero",
        "weapon": "Static Mist",
        "echo_sets": ["Moonlit Clouds (5pc) — buffer", "Sierra Gale (5pc) — DPS"],
        "echo_mains": {
            "4-cost": "Aero DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Aero buffer / sub-DPS. Main echo Impermanence Heron or Nightmare: Feilian Beringal. Static Mist (pistol buffer) is BiS.",
        "patch": "1.0",
    },
    "Chixia": {
        "role": "Main DPS",
        "element": "Fusion",
        "weapon": "Static Mist",
        "echo_sets": ["Molten Rift (3pc) + Lingering Tunes (2pc)", "Molten Rift (5pc)"],
        "echo_mains": {
            "4-cost": "Fusion DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "F2P Fusion DPS. Main echo Inferno Rider. Static Mist BiS; Novaburst / Pistols#26 are alts.",
        "patch": "1.0",
    },
    "Yangyang": {
        "role": "Support / Sub-DPS",
        "element": "Aero",
        "weapon": "Emerald of Genesis",
        "echo_sets": ["Moonlit Clouds (5pc)"],
        "echo_mains": {
            "4-cost": "ATK%",
            "3-cost": "ATK%",
            "3-cost-alt": "Energy Regen",
            "1-cost": "ATK%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["Energy Regen", "CRIT Rate", "CRIT DMG", "ATK%"],
        "notes": "Aero sub-DPS / buffer. Main echo Impermanence Heron. ER ~140%. Emerald of Genesis BiS; Blazing Brilliance for a damage lean.",
        "patch": "1.0",
    },
    "Taoqi": {
        "role": "Tank / Support",
        "element": "Havoc",
        "weapon": "Dauntless Evernight",
        "echo_sets": ["Moonlit Clouds (5pc)", "Rejuvenating Glow (5pc)"],
        "echo_mains": {
            "4-cost": "DEF%",
            "3-cost": "DEF%",
            "3-cost-alt": "Energy Regen",
            "1-cost": "DEF%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["DEF%", "Energy Regen", "HP%", "CRIT Rate"],
        "notes": "DEF-scaling shielder/support. Main echo Impermanence Heron. Dauntless Evernight (DEF) is the F2P BiS; Discord for a pure-buffer build.",
        "patch": "1.0",
    },
    "Jianxin": {
        "role": "Tank / Support",
        "element": "Aero",
        "weapon": "Abyss Surges",
        "echo_sets": ["Moonlit Clouds (5pc)"],
        "echo_mains": {
            "4-cost": "ATK%",
            "3-cost": "ATK%",
            "3-cost-alt": "Energy Regen",
            "1-cost": "ATK%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["Energy Regen", "ATK%", "CRIT Rate", "CRIT DMG"],
        "notes": "Aero hybrid: shields + CC, Outro buffs Liberation DMG. Built ATK%/ER as a Liberation sub-DPS/buffer. Main echo Impermanence Heron. Verity's Handle is an alt weapon.",
        "patch": "1.0",
    },
    "Lucilla": {
        "role": "Sub-DPS / Support",
        "element": "Glacio",
        "weapon": "Freeze Frame",
        "echo_sets": ["Wishes of Quiet Snowfall (5pc) — Glacio Chafe team", "Dream of the Lost (5pc) — Phrolova team"],
        "echo_mains": {
            "4-cost": "CRIT Rate / CRIT DMG",
            "3-cost": "Glacio DMG%",
            "3-cost-alt": "Glacio DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Flat ATK"],
        "notes": "Echo set depends on team: Wishes of Quiet Snowfall with Glacio Chafe, Dream of the Lost with Phrolova. In Echo mode prioritise ATK over Basic DMG%.",
        "patch": "3.x",
    },
    "Cartethyia": {
        "role": "Main DPS",
        "element": "Aero",
        "weapon": "Defier's Thorn",
        "echo_sets": ["Windward Pilgrimage (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Aero DMG%",
            "3-cost-alt": "Aero DMG%",
            "1-cost": "HP%",
            "1-cost-2": "HP%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "HP%", "Energy Regen"],
        "notes": "HP scaler — aim ~50k HP and a 70/270 crit ratio. Main echo Reminiscence: Fleurdelys. Energy Regen to ~110%. Avoid flat ATK entirely.",
        "patch": "3.0",
    },
    "Phrolova": {
        "role": "Main DPS",
        "element": "Havoc",
        "weapon": "Lethean Elegy",
        "echo_sets": ["Dream of the Lost (3pc) + Midnight Veil (2pc)", "Dream of the Lost (3pc) + Havoc Eclipse (2pc)"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Havoc DMG%",
            "3-cost-alt": "Havoc DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Echo Skill DPS. Main echo Nightmare: Hecate. R1 has 57.3% base Crit Rate — prioritise Crit Rate ONLY until capped, then Crit DMG.",
        "patch": "3.3",
    },
    "Denia": {
        "role": "Main DPS",
        "element": "Fusion",
        "weapon": "Forged Dwarf Star",
        "echo_sets": ["Chromatic Foam (5pc) — Fusion Burst", "Reel of Spliced Memories (5pc) — Tune Strain"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Fusion DMG%",
            "3-cost-alt": "Fusion DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Echo set is team-dependent: Chromatic Foam (Fusion Burst) or Reel of Spliced Memories (Tune Strain). Energy Regen 120–125%. Flaming Clawprint / Moonlit Clouds are alternatives.",
        "patch": "3.x",
    },
    "Yinlin": {
        "role": "Sub-DPS / Support",
        "element": "Electro",
        "weapon": "Stringmaster",
        "echo_sets": ["Void Thunder (5pc)"],
        "echo_mains": {
            "4-cost": "Electro DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Off-field Electro sub-DPS via coordinated attacks. Stringmaster is BiS; Cosmic Ripples is a strong alternative.",
        "patch": "1.1",
    },
    "Buling": {
        "role": "Support / Healer",
        "element": "Electro",
        "weapon": "Stellar Symphony",
        "echo_sets": ["Rejuvenating Glow (5pc)"],
        "echo_mains": {
            "4-cost": "Healing Bonus%",
            "3-cost": "Energy Regen",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["Energy Regen", "ATK%", "Flat ATK", "CRIT Rate"],
        "notes": "Top-tier 4★ healer. Weapon Stellar Symphony (Variation is a solid budget alt). Aim Energy Regen ~150%, ATK >1800.",
    },
    "Lucy": {
        "role": "Main DPS",
        "element": "Spectro",
        "weapon": "Spectral Trigger",
        "echo_sets": ["Spectro 1+2+2 Sonata mix — main echo Nightmare: Adam Smasher"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Spectro DMG%",
            "3-cost-alt": "Spectro DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Collab DPS — Heavy Attack & Hack DMG focused. Uses the 1+2+2 single-piece Sonata system; main echo Nightmare: Adam Smasher. Spectral Trigger is BiS.",
        "patch": "3.4",
    },
    "Rebecca": {
        "role": "Sub-DPS / Support",
        "element": "Electro",
        "weapon": "Skull Thrasher",
        "echo_sets": ["Shadow of Shattered Dreams (1pc) + Celestial Light (2pc) + Lingering Tunes (2pc)"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Electro DMG%",
            "3-cost-alt": "Electro DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Collab Electro sub-DPS. Skull Thrasher gives Basic Attack DMG + team ATK buff. Main echo Adam Smasher. Energy Regen ~125%; roll Basic Attack DMG where possible.",
        "patch": "3.4",
    },
    "Zhezhi": {
        "role": "Sub-DPS / Support",
        "element": "Glacio",
        "weapon": "Rime-Draped Sprouts",
        "echo_sets": ["Freezing Frost (5pc)", "Empyrean Anthem (5pc) — sub-DPS"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Glacio DMG%",
            "3-cost-alt": "Glacio DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Coordinated-attack Glacio sub-DPS. Main echo Nightmare: Lampylumen Myriad. Keep a 1:2 crit ratio; one 3-cost can swap to Energy Regen if needed.",
        "patch": "1.2",
    },
    "Lupa": {
        "role": "Sub-DPS / Support",
        "element": "Fusion",
        "weapon": "Wildfire Mark",
        "echo_sets": ["Flaming Clawprint (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Fusion DMG%",
            "3-cost-alt": "Fusion DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Fusion DPS/buffer with team-wide DMG bonus. Main echo Lioness of Glory (4-cost). Discord / Waning Redshift are budget weapons.",
        "patch": "3.1",
    },
    "Hiyuki": {
        "role": "Main DPS",
        "element": "Glacio",
        "weapon": "Frostburn",
        "echo_sets": ["Wishes of Quiet Snowfall (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Glacio DMG%",
            "3-cost-alt": "Glacio DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["Energy Regen", "CRIT DMG", "CRIT Rate", "ATK%"],
        "notes": "Glacio Chafe DPS. Main echo Reminiscence: Threnodian – Voidborne Construct. ER ~120%, crit ~70:250. Emerald of Genesis is the budget weapon.",
        "patch": "3.3",
    },
    "Aemeath": {
        "role": "Main DPS",
        "element": "Fusion",
        "weapon": "Everbright Polestar",
        "echo_sets": ["Trailblazing Star (3pc) + Molten Rift (2pc)", "Molten Rift (5pc) — budget"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Fusion DMG%",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Resonance Liberation Fusion DPS. ER ~120%, keep a 1:2 crit ratio. Molten Rift is the budget set.",
        "patch": "3.1",
    },
    "Augusta": {
        "role": "Main DPS",
        "element": "Electro",
        "weapon": "Thunderflare Dominion",
        "echo_sets": ["Crown of Valor (3pc) + Void Thunder (2pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Electro DMG%",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "ATK / Heavy-Attack Electro DPS. Aim 70–80% Crit Rate, ATK >2100, ~250% Crit DMG. Roll Heavy Attack DMG.",
        "patch": "2.6",
    },
    "Chisa": {
        "role": "Sub-DPS / Support",
        "element": "Havoc",
        "weapon": "Kumokiri",
        "echo_sets": ["Thread of Severed Fate (3pc) + Sun-sinking Eclipse (2pc)", "Rejuvenating Glow (5pc) — support"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Havoc DMG%",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Negative-status support/sub-DPS. Kumokiri BiS (Wildfire Mark alt). Thread of Severed Fate for damage, Rejuvenating Glow for a pure-support build.",
        "patch": "2.8",
    },
    "Ciaccona": {
        "role": "Sub-DPS / Support",
        "element": "Aero",
        "weapon": "Woodland Aria",
        "echo_sets": ["Gusts of Welkin (5pc)", "Moonlit Clouds (5pc) — Spectro Frazzle teams"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Aero DMG%",
            "3-cost-alt": "Aero DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Aero Erosion sub-DPS. Woodland Aria BiS (Phasic Homogenizer close 2nd). Moonlit Clouds when used as a buffer in Spectro Frazzle teams.",
        "patch": "3.0",
    },
    "Galbrena": {
        "role": "Main DPS",
        "element": "Fusion",
        "weapon": "Lux & Umbra",
        "echo_sets": ["Flamewing's Shadow (5pc)", "Flamewing's Shadow (3pc) + Molten Rift (2pc)"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Fusion DMG%",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Echo Skill / Heavy Attack Fusion DPS. Main echo Corrosaurus (3-cost). ER ~120%. Roll Heavy Attack DMG.",
        "patch": "3.x",
    },
    "Iuno": {
        "role": "Sub-DPS / Main DPS",
        "element": "Aero",
        "weapon": "Moongazer's Sigil",
        "echo_sets": ["Crown of Valor (3pc) + Sierra Gale (2pc)"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Aero DMG%",
            "3-cost-alt": "Aero DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Resonance Liberation Aero sub-DPS (can hypercarry). Main echo Lady of the Sea (4-cost). ER ~120–125%; roll Res Liberation DMG.",
        "patch": "3.x",
    },
    "Lumi": {
        "role": "Support / Sub-DPS",
        "element": "Electro",
        "weapon": "Discord",
        "echo_sets": ["Moonlit Clouds (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Electro DMG%",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["Energy Regen", "ATK%", "CRIT Rate", "CRIT DMG"],
        "notes": "4★ Resonance-Skill buffer for quickswap teams. Moonlit Clouds + Discord enable fast rotations; buffs next unit's ATK via Outro.",
        "patch": "2.x",
    },
    "Luuk Herssen": {
        "role": "Main DPS",
        "element": "Spectro",
        "weapon": "Daybreaker's Spine",
        "echo_sets": ["Rite of Gilded Revelation (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Spectro DMG%",
            "3-cost-alt": "Spectro DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Aerial Basic-Attack Spectro DPS. Main echo Twin Nova: Nebulous Cannon (3-cost). ER ~120%; roll Basic Attack DMG. Alts: Pulsation Bracer, Abyss Surges.",
        "patch": "3.1",
    },
    "Lynae": {
        "role": "Sub-DPS / Support",
        "element": "Spectro",
        "weapon": "Spectrum Blaster",
        "echo_sets": ["Pact of Neonlight Leap (5pc)", "Moonlit Clouds (5pc) — buffer"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Spectro DMG%",
            "3-cost-alt": "Spectro DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Spectro sub-DPS/buffer. Main echo Hyvatia (team all-type buff). Spectrum Blaster BiS; ER ~120%; roll Basic Attack DMG. Static Mist if used purely as a buffer.",
        "patch": "3.2",
    },
    "Mornye": {
        "role": "Support / Healer",
        "element": "Fusion",
        "weapon": "Starfield Calibrator",
        "echo_sets": ["Halo of Starry Radiance (5pc)", "Rejuvenating Glow (5pc)"],
        "echo_mains": {
            "4-cost": "Healing Bonus%",
            "3-cost": "Energy Regen",
            "3-cost-alt": "Energy Regen",
            "1-cost": "DEF%",
            "1-cost-2": "DEF%",
        },
        "substats": ["Energy Regen", "DEF%", "Flat DEF", "CRIT DMG"],
        "notes": "DEF-scaling healer/buffer. Needs ~260% total Energy Regen to max team buffs. Discord is the budget weapon.",
        "patch": "3.0",
    },
    "Qiuyuan": {
        "role": "Sub-DPS / Support",
        "element": "Aero",
        "weapon": "Emerald Sentence",
        "echo_sets": ["Law of Harmony (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Aero DMG%",
            "3-cost-alt": "Aero DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Echo-Skill amplifier / Aero sub-DPS. ER ~130%; aim ≥65% Crit Rate; roll Heavy Attack DMG. Core to Echo-Skill teams (Sigrika, Galbrena, Phrolova, Cantarella).",
        "patch": "3.x",
    },
    "Rover (Aero)": {
        "role": "Sub-DPS / Support",
        "element": "Aero",
        "weapon": "Bloodpact's Pledge",
        "echo_sets": ["Windward Pilgrimage (5pc) — sub-DPS", "Rejuvenating Glow (5pc) — support healer"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Aero DMG%",
            "3-cost-alt": "Aero DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Aero Erosion sub-DPS / healer hybrid. Main echo Reminiscence: Fleurdelys (sub-DPS) or Fallacy of No Return (support). Best support healer in Aero Erosion teams.",
        "patch": "2.2",
    },
    "Sigrika": {
        "role": "Main DPS",
        "element": "Aero",
        "weapon": "Solsworn Ciphers",
        "echo_sets": ["Sound of True Name (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Energy Regen",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Echo-Skill Aero DPS. Needs ~150% Energy Regen for her max Echo Skill DMG bonus. Main echo Nameless Explorer. Blazing Justice is a strong alt weapon.",
        "patch": "3.2",
    },
    "Youhu": {
        "role": "Support / Healer",
        "element": "Glacio",
        "weapon": "Abyss Surges",
        "echo_sets": ["Rejuvenating Glow (5pc)", "Freezing Frost (5pc)"],
        "echo_mains": {
            "4-cost": "Healing Bonus%",
            "3-cost": "Energy Regen",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["Energy Regen", "ATK%", "CRIT Rate", "CRIT DMG"],
        "notes": "4★ coordinated-attack support/healer. Main echo Lampylumen Myriad (or Bell-Borne Geochelone for a pure healer). Marcato is the budget weapon. Best in coordinated-attack teams.",
        "patch": "1.x",
    },
    "Yuanwu": {
        "role": "Support / Sub-DPS",
        "element": "Electro",
        "weapon": "Amity Accord",
        "echo_sets": ["Moonlit Clouds (5pc) — support", "Void Thunder (5pc) — damage"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Energy Regen",
            "3-cost-alt": "Electro DMG%",
            "1-cost": "DEF%",
            "1-cost-2": "DEF%",
        },
        "substats": ["Energy Regen", "DEF%", "CRIT Rate", "CRIT DMG"],
        "notes": "DEF-scaling defensive Electro support. Main echo Tempest Mephis. Amity Accord (DEF) BiS; Abyss Surges for more Energy Regen.",
        "patch": "1.0",
    },
}


def get_build(name: str) -> dict | None:
    return BUILDS.get(name)


def get_all_names() -> list[str]:
    return sorted(ALL_RESONATORS)
