"""
Static build database sourced from prydwen.gg.
Used by /build command. Update this file as the meta shifts.
"""

ALL_RESONATORS = [
    "Aalto", "Aemeath", "Augusta", "Baizhi", "Brant", "Buling",
    "Calcharo", "Camellya", "Cantarella", "Carlotta", "Cartethyia",
    "Changli", "Chisa", "Chixia", "Ciaccona", "Danjin", "Denia",
    "Encore", "Galbrena", "Hiyuki", "Iuno", "Jianxin", "Jinhsi", "Jiyan",
    "Lingyang", "Lucilla", "Lucy", "Lumi", "Lupa", "Luuk Herssen",
    "Lynae", "Mornye", "Mortefi", "Phoebe", "Phrolova", "Qiuyuan",
    "Rebecca", "Roccia", "Rover (Aero)", "Rover (Havoc)", "Rover (Spectro)",
    "Sanhua", "Sigrika", "Taoqi", "The Shorekeeper", "Verina",
    "Xiangli Yao", "Yangyang", "Yinlin", "Youhu", "Yuanwu", "Zani", "Zhezhi",
]

# slug used in prydwen URLs (lowercase, spaces→hyphens, parens stripped)
def prydwen_slug(name: str) -> str:
    import re
    s = name.lower()
    s = re.sub(r"[()]+", "", s)
    s = re.sub(r"\s+", "-", s.strip())
    s = re.sub(r"-+", "-", s)
    return s


def prydwen_url(name: str) -> str:
    return f"https://www.prydwen.gg/wuthering-waves/characters/{prydwen_slug(name)}"


# Build data: echo_sets, main_stats per slot, priority substats, notes
# Source: prydwen.gg — June 2026
BUILDS: dict[str, dict] = {
    "Jiyan": {
        "role": "Main DPS",
        "element": "Aero",
        "weapon": "Verdant Summit",
        "echo_sets": ["Sierra Gale (5pc)"],
        "echo_mains": {
            "4-cost": "Aero DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "Aero DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Resonance Liberation > Forte Circuit ≈ Resonance Skill > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Roaring Rock Fist ×46 (boss), Pecok Flower ×60, Howler Cores ×32, 170k Shell.\n**Talents:** Waveworn Residue ×175 (forgery), Monument Bell ×26 (weekly boss), Howler Cores ×150, 2.03M Shell.",
        "notes": "Heavy-Attack Aero DPS. Main echo Nightmare: Feilian Beringal. Aim 70%+ Crit Rate; stack Energy Regen for ult rotation.",
        "patch": "3.2",
    },
    "Carlotta": {
        "role": "Main DPS",
        "element": "Glacio",
        "weapon": "The Last Dance",
        "echo_sets": ["Frosty Resolve (5pc)", "Freezing Frost (5pc)"],
        "echo_mains": {
            "4-cost": "Glacio DMG%",
            "3-cost": "CRIT Rate",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT DMG", "CRIT Rate", "ATK%", "Energy Regen"],
        "skill_priority": "Resonance Liberation ≈ Resonance Skill > Forte Circuit > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Platinum Core ×46 (boss), Sword Acorus ×60, Polygon Cores ×32, 170k Shell.\n**Talents:** Phlogiston ×175 (forgery), The Netherworld's Stare ×26 (weekly boss), Polygon Cores ×150, 2.03M Shell.",
        "notes": "Resonance Skill Glacio DPS. Main echo Sentry Construct (Frosty Resolve). Prioritise CRIT DMG after ~70% Crit Rate.",
        "patch": "2.0",
    },
    "Changli": {
        "role": "Main DPS / Flex",
        "element": "Fusion",
        "weapon": "Blazing Brilliance",
        "echo_sets": ["Molten Rift (5pc)"],
        "echo_mains": {
            "4-cost": "Fusion DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Resonance Skill ≈ Forte Circuit > Resonance Liberation > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Rage Tacet Core ×46 (boss), Pavo Plum ×60, Rings ×32, 170k Shell.\n**Talents:** Metallic Drip ×175 (forgery), Sentinel's Dagger ×26 (weekly boss), Rings ×150, 2.03M Shell.",
        "notes": "High energy cost — prioritise Energy Regen as secondary substat.",
        "patch": "1.3",
    },
    "Camellya": {
        "role": "Main DPS",
        "element": "Havoc",
        "weapon": "Red Spring",
        "echo_sets": ["Sun-sinking Eclipse (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Havoc DMG%",
            "3-cost-alt": "Havoc DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Resonance Skill > Forte Circuit > Resonance Liberation > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Topological Confinement ×46 (boss), Nova ×60, Whisperin Cores ×32, 170k Shell.\n**Talents:** Cadence ×175 (forgery), Dreamless Feather ×26 (weekly boss), Whisperin Cores ×150, 2.03M Shell.",
        "notes": "Basic-attack Havoc DPS (~80% of damage is Basic Attack). Main echo Dreamless (Crownless for a higher ceiling). Somnoire Anchor is the F2P weapon.",
        "patch": "2.0",
    },
    "Jinhsi": {
        "role": "Main DPS",
        "element": "Spectro",
        "weapon": "Ages of Harvest",
        "echo_sets": ["Celestial Light (5pc)"],
        "echo_mains": {
            "4-cost": "Spectro DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT DMG", "CRIT Rate", "ATK%", "Energy Regen"],
        "skill_priority": "Forte Circuit > Resonance Liberation > Resonance Skill > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Elegy Tacet Core ×46 (boss), Loong's Pearl ×60, Howler Cores ×32, 170k Shell.\n**Talents:** Waveworn Residue ×175 (forgery), Sentinel's Dagger ×26 (weekly boss), Howler Cores ×150, 2.03M Shell.",
        "notes": "Stack Incandescence before using ult for maximum damage.",
        "patch": "1.3",
    },
    "Xiangli Yao": {
        "role": "Main DPS",
        "element": "Electro",
        "weapon": "Verity's Handle",
        "echo_sets": ["Void Thunder (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Electro DMG%",
            "3-cost-alt": "Electro DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Resonance Liberation ≈ Forte Circuit > Resonance Skill > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Hidden Thunder Tacet Core ×46 (boss), Violet Coral ×60, Whisperin Cores ×32, 170k Shell.\n**Talents:** Waveworn Residue ×175 (forgery), Unending Destruction ×26 (weekly boss), Whisperin Cores ×150, 2.03M Shell.",
        "notes": "Resonance Liberation Electro DPS. Main echo Thundering Mephis. Stack Energy Regen for ult uptime. BiS partner: Yinlin.",
        "patch": "1.2",
    },
    "Phoebe": {
        "role": "Main DPS",
        "element": "Spectro",
        "weapon": "Luminous Hymn",
        "echo_sets": ["Eternal Radiance (5pc)"],
        "echo_mains": {
            "4-cost": "Spectro DMG%",
            "3-cost": "Spectro DMG%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Forte Circuit > Resonance Skill > Resonance Liberation > Intro Skill > Basic Attack",
        "materials": "**Ascension:** Cleansing Conch ×46 (boss), Firecracker Jewelweed ×60, Whisperin Cores ×32, 170k Shell.\n**Talents:** Helix ×175 (forgery), Sentinel's Dagger ×26 (weekly boss), Whisperin Cores ×150, 2.03M Shell.",
        "notes": "Spectro Frazzle DPS. Main echo Capitaneus (Nightmare: Mourning Aix alt). Moonlit Clouds when played as a sub-DPS.",
        "patch": "2.2",
    },
    "Cantarella": {
        "role": "Sub-DPS / Support",
        "element": "Havoc",
        "weapon": "Whispers of Sirens",
        "echo_sets": ["Midnight Veil (5pc)"],
        "echo_mains": {
            "4-cost": "Havoc DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Forte Circuit ≈ Resonance Liberation > Resonance Skill > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Cleansing Conch ×46 (boss), Seaside Cendrelis ×60, Polygon Cores ×32, 170k Shell.\n**Talents:** Helix ×175 (forgery), When Irises Bloom ×26 (weekly boss), Polygon Cores ×150, 2.03M Shell.",
        "notes": "Havoc Echo-Skill sub-DPS/healer. Main echo Lorelei. Cosmic Ripples / Rime-Draped Sprouts are alt weapons. Pairs with Phrolova.",
        "patch": "2.2",
    },
    "Calcharo": {
        "role": "Main DPS",
        "element": "Electro",
        "weapon": "Lustrous Razor",
        "echo_sets": ["Void Thunder (5pc)"],
        "echo_mains": {
            "4-cost": "Electro DMG%",
            "3-cost": "CRIT Rate",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT DMG", "CRIT Rate", "ATK%", "Energy Regen"],
        "skill_priority": "Resonance Liberation ≈ Forte Circuit > Resonance Skill > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Thundering Tacet Core ×46 (boss), Iris ×60, Rings ×32, 170k Shell.\n**Talents:** Waveworn Residue ×175 (forgery), Monument Bell ×26 (weekly boss), Rings ×150, 2.03M Shell.",
        "notes": "Strong burst window; save ult for max stack usage.",
        "patch": "1.0",
    },
    "Encore": {
        "role": "Main DPS",
        "element": "Fusion",
        "weapon": "Stringmaster",
        "echo_sets": ["Molten Rift (5pc)"],
        "echo_mains": {
            "4-cost": "Fusion DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Resonance Liberation > Forte Circuit ≈ Resonance Skill > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Rage Tacet Core ×46 (boss), Pecok Flower ×60, Whisperin Cores ×32, 170k Shell.\n**Talents:** Helix ×175 (forgery), Unending Destruction ×26 (weekly boss), Whisperin Cores ×150, 2.03M Shell.",
        "notes": "Fusion DPS. Main echo Inferno Rider. Stringmaster BiS; Cosmic Ripples is a strong alt. Weave skills for Molten Rift uptime.",
        "patch": "1.0",
    },
    "Danjin": {
        "role": "Main DPS",
        "element": "Havoc",
        "weapon": "Blazing Brilliance",
        "echo_sets": ["Sun-sinking Eclipse (5pc)"],
        "echo_mains": {
            "4-cost": "Havoc DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Flat ATK"],
        "notes": "Havoc burst DPS. Main echo Crownless. Blazing Brilliance has ~100% uptime on her; Red Spring / Emerald of Genesis are alts.",
        "patch": "1.0",
    },
    "Lingyang": {
        "role": "Main DPS",
        "element": "Glacio",
        "weapon": "Abyss Surges",
        "echo_sets": ["Freezing Frost (5pc)"],
        "echo_mains": {
            "4-cost": "Glacio DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Forte Circuit > Resonance Skill ≈ Basic Attack > Resonance Liberation > Intro Skill",
        "materials": "**Ascension:** Sound-Keeping Tacet Core ×46 (boss), Coriolus ×60, Whisperin Cores ×32, 170k Shell.\n**Talents:** Cadence ×175 (forgery), Unending Destruction ×26 (weekly boss), Whisperin Cores ×150, 2.03M Shell.",
        "notes": "Airborne DPS — use ult then launch combos mid-air.",
        "patch": "1.0",
    },
    "Sanhua": {
        "role": "Sub-DPS / Support",
        "element": "Glacio",
        "weapon": "Emerald of Genesis",
        "echo_sets": ["Moonlit Clouds (5pc) — buffer", "Freezing Frost (5pc) — damage"],
        "echo_mains": {
            "4-cost": "Glacio DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Basic-Attack buffer / sub-DPS. Main echo Impermanence Heron (Moonlit Clouds). Overture is a strong alt weapon for faster Outro.",
        "patch": "1.0",
    },
    "Mortefi": {
        "role": "Sub-DPS / Support",
        "element": "Fusion",
        "weapon": "Static Mist",
        "echo_sets": ["Moonlit Clouds (5pc)", "Empyrean Anthem (5pc)"],
        "echo_mains": {
            "4-cost": "Fusion DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Heavy-Attack amplifier support. Main echo Impermanence Heron. Cadenza / Relativistic Jet are 4★ alt weapons.",
        "patch": "1.0",
    },
    "Verina": {
        "role": "Support / Healer",
        "element": "Spectro",
        "weapon": "Stellar Symphony",
        "echo_sets": ["Rejuvenating Glow (5pc)"],
        "echo_mains": {
            "4-cost": "Healing Bonus%",
            "3-cost": "HP%",
            "3-cost-alt": "ATK%",
            "1-cost": "HP%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["Energy Regen", "HP%", "ATK%", "CRIT Rate"],
        "notes": "Universal buffer/healer; ult gives team-wide DMG bonus. Main echo Bell-Borne Geochelone. Variation is the top budget/F2P weapon.",
        "patch": "1.0",
    },
    "The Shorekeeper": {
        "role": "Support / Healer",
        "element": "Spectro",
        "weapon": "Stellar Symphony",
        "echo_sets": ["Rejuvenating Glow (5pc)"],
        "echo_mains": {
            "4-cost": "Healing Bonus%",
            "3-cost": "HP%",
            "3-cost-alt": "Energy Regen",
            "1-cost": "HP%",
            "1-cost-2": "HP%",
        },
        "substats": ["Energy Regen", "HP%", "ATK%", "CRIT Rate"],
        "notes": "Top-tier healer/buffer. Main echo Fallacy of No Return. Stack Energy Regen toward ~250% for the Stellarealm crit buff. Variation is the budget weapon.",
        "patch": "1.3",
    },
    "Baizhi": {
        "role": "Support / Healer",
        "element": "Glacio",
        "weapon": "Stellar Symphony",
        "echo_sets": ["Rejuvenating Glow (5pc)"],
        "echo_mains": {
            "4-cost": "Healing Bonus%",
            "3-cost": "HP%",
            "3-cost-alt": "Energy Regen",
            "1-cost": "HP%",
            "1-cost-2": "HP%",
        },
        "substats": ["Energy Regen", "HP%", "ATK%", "CRIT Rate"],
        "notes": "F2P-friendly healer. Main echo Bell-Borne Geochelone. ER ~100–110%. Variation is the craftable budget weapon.",
        "patch": "1.0",
    },
    "Rover (Havoc)": {
        "role": "Main DPS",
        "element": "Havoc",
        "weapon": "Emerald of Genesis",
        "echo_sets": ["Sun-sinking Eclipse (5pc)"],
        "echo_mains": {
            "4-cost": "Havoc DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Strong free unit. Forte circuit charges quickly in combat.",
        "patch": "1.1",
    },
    "Rover (Spectro)": {
        "role": "Sub-DPS / Support",
        "element": "Spectro",
        "weapon": "Emerald of Genesis",
        "echo_sets": ["Moonlit Clouds (5pc) — sub-DPS buffer", "Eternal Radiance (5pc) — DPS"],
        "echo_mains": {
            "4-cost": "Spectro DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Spectro Frazzle sub-DPS. Moonlit Clouds (buffer) or Eternal Radiance (damage). Main echo Impermanence Heron. ER-hungry; Blazing Brilliance for the damage build.",
        "patch": "1.0",
    },
    "Roccia": {
        "role": "Sub-DPS / Support",
        "element": "Havoc",
        "weapon": "Tragicomedy",
        "echo_sets": ["Midnight Veil (5pc)", "Moonlit Clouds (5pc) — buffer"],
        "echo_mains": {
            "4-cost": "Havoc DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Forte Circuit ≈ Resonance Liberation > Resonance Skill > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Cleansing Conch ×46 (boss), Firecracker Jewelweed ×60, Tidal Residuum ×32, 170k Shell.\n**Talents:** Cadence ×175 (forgery), The Netherworld's Stare ×26 (weekly boss), Tidal Residuum ×150, 2.03M Shell.",
        "notes": "Havoc sub-DPS/buffer. Main echo Nightmare: Impermanence Heron (Midnight Veil) or Impermanence Heron (Moonlit Clouds). Abyss Surges is an alt weapon.",
        "patch": "2.0",
    },
    "Brant": {
        "role": "Main DPS",
        "element": "Fusion",
        "weapon": "Unflickering Valor",
        "echo_sets": ["Tidebreaking Courage (5pc) — needs ~250% ER", "Molten Rift (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Energy Regen",
            "3-cost-alt": "Fusion DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "Energy Regen", "ATK%"],
        "skill_priority": "Forte Circuit > Basic Attack ≈ Resonance Liberation > Resonance Skill > Intro Skill",
        "materials": "**Ascension:** Blazing Bone ×46 (boss), Golden Fleece ×60, Tidal Residuum ×32, 170k Shell.\n**Talents:** Metallic Drip ×175 (forgery), The Netherworld's Stare ×26 (weekly boss), Tidal Residuum ×150, 2.03M Shell.",
        "notes": "Basic-attack Fusion DPS with heal/shield utility. Tidebreaking Courage needs ~250% Energy Regen; Molten Rift is the lower-investment alt. Priority: Crit > ER > Basic Attack DMG.",
        "patch": "2.1",
    },
    "Zani": {
        "role": "Main DPS",
        "element": "Spectro",
        "weapon": "Blazing Justice",
        "echo_sets": ["Eternal Radiance (5pc)", "Celestial Light (5pc)"],
        "echo_mains": {
            "4-cost": "Spectro DMG%",
            "3-cost": "Spectro DMG%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Forte Circuit > Resonance Liberation ≈ Resonance Skill > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Platinum Core ×46 (boss), Sword Acorus ×60, Polygon Cores ×32, 170k Shell.\n**Talents:** Cadence ×175 (forgery), The Netherworld's Stare ×26 (weekly boss), Polygon Cores ×150, 2.03M Shell.",
        "notes": "Spectro Frazzle DPS. Main echo Capitaneus (3-cost). Keep Energy Regen ~130%.",
        "patch": "2.4",
    },
    "Aalto": {
        "role": "Sub-DPS / Support",
        "element": "Aero",
        "weapon": "Static Mist",
        "echo_sets": ["Moonlit Clouds (5pc) — buffer", "Sierra Gale (5pc) — DPS"],
        "echo_mains": {
            "4-cost": "Aero DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Aero buffer / sub-DPS. Main echo Impermanence Heron or Nightmare: Feilian Beringal. Static Mist (pistol buffer) is BiS.",
        "patch": "1.0",
    },
    "Chixia": {
        "role": "Main DPS",
        "element": "Fusion",
        "weapon": "Static Mist",
        "echo_sets": ["Molten Rift (3pc) + Lingering Tunes (2pc)", "Molten Rift (5pc)"],
        "echo_mains": {
            "4-cost": "Fusion DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "F2P Fusion DPS. Main echo Inferno Rider. Static Mist BiS; Novaburst / Pistols#26 are alts.",
        "patch": "1.0",
    },
    "Yangyang": {
        "role": "Support / Sub-DPS",
        "element": "Aero",
        "weapon": "Emerald of Genesis",
        "echo_sets": ["Moonlit Clouds (5pc)"],
        "echo_mains": {
            "4-cost": "ATK%",
            "3-cost": "ATK%",
            "3-cost-alt": "Energy Regen",
            "1-cost": "ATK%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["Energy Regen", "CRIT Rate", "CRIT DMG", "ATK%"],
        "notes": "Aero sub-DPS / buffer. Main echo Impermanence Heron. ER ~140%. Emerald of Genesis BiS; Blazing Brilliance for a damage lean.",
        "patch": "1.0",
    },
    "Taoqi": {
        "role": "Tank / Support",
        "element": "Havoc",
        "weapon": "Dauntless Evernight",
        "echo_sets": ["Moonlit Clouds (5pc)", "Rejuvenating Glow (5pc)"],
        "echo_mains": {
            "4-cost": "DEF%",
            "3-cost": "DEF%",
            "3-cost-alt": "Energy Regen",
            "1-cost": "DEF%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["DEF%", "Energy Regen", "HP%", "CRIT Rate"],
        "notes": "DEF-scaling shielder/support. Main echo Impermanence Heron. Dauntless Evernight (DEF) is the F2P BiS; Discord for a pure-buffer build.",
        "patch": "1.0",
    },
    "Jianxin": {
        "role": "Tank / Support",
        "element": "Aero",
        "weapon": "Abyss Surges",
        "echo_sets": ["Moonlit Clouds (5pc)"],
        "echo_mains": {
            "4-cost": "ATK%",
            "3-cost": "ATK%",
            "3-cost-alt": "Energy Regen",
            "1-cost": "ATK%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["Energy Regen", "ATK%", "CRIT Rate", "CRIT DMG"],
        "notes": "Aero hybrid: shields + CC, Outro buffs Liberation DMG. Built ATK%/ER as a Liberation sub-DPS/buffer. Main echo Impermanence Heron. Verity's Handle is an alt weapon.",
        "patch": "1.0",
    },
    "Lucilla": {
        "role": "Sub-DPS / Support",
        "element": "Glacio",
        "weapon": "Freeze Frame",
        "echo_sets": ["Wishes of Quiet Snowfall (5pc) — Glacio Chafe team", "Dream of the Lost (5pc) — Phrolova team"],
        "echo_mains": {
            "4-cost": "CRIT Rate / CRIT DMG",
            "3-cost": "Glacio DMG%",
            "3-cost-alt": "Glacio DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Flat ATK"],
        "skill_priority": "Resonance Liberation > Forte Circuit > Resonance Skill > Basic Attack ≈ Intro Skill",
        "materials": "**Ascension:** Suncoveter's Reach ×46 (boss), Forget-Me-Not ×60, Mech Cores ×32, 170k Shell.\n**Talents:** Strings ×175 (forgery), We Who Question ×26 (weekly boss), Mech Cores ×150, 2.03M Shell.",
        "notes": "Echo set depends on team: Wishes of Quiet Snowfall with Glacio Chafe, Dream of the Lost with Phrolova. In Echo mode prioritise ATK over Basic DMG%.",
        "patch": "3.x",
    },
    "Cartethyia": {
        "role": "Main DPS",
        "element": "Aero",
        "weapon": "Defier's Thorn",
        "echo_sets": ["Windward Pilgrimage (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Aero DMG%",
            "3-cost-alt": "Aero DMG%",
            "1-cost": "HP%",
            "1-cost-2": "HP%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "HP%", "Energy Regen"],
        "skill_priority": "Forte Circuit > Basic Attack ≈ Resonance Liberation > Resonance Skill > Intro Skill",
        "materials": "**Ascension:** Unfading Glory ×46 (boss), Bamboo Iris ×60, Tidal Residuum ×32, 170k Shell.\n**Talents:** Metallic Drip ×175 (forgery), When Irises Bloom ×26 (weekly boss), Tidal Residuum ×150, 2.03M Shell.",
        "notes": "HP scaler — aim ~50k HP and a 70/270 crit ratio. Main echo Reminiscence: Fleurdelys. Energy Regen to ~110%. Avoid flat ATK entirely.",
        "patch": "3.0",
    },
    "Phrolova": {
        "role": "Main DPS",
        "element": "Havoc",
        "weapon": "Lethean Elegy",
        "echo_sets": ["Dream of the Lost (3pc) + Midnight Veil (2pc)", "Dream of the Lost (3pc) + Havoc Eclipse (2pc)"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Havoc DMG%",
            "3-cost-alt": "Havoc DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Resonance Liberation > Basic Attack ≈ Forte Circuit > Intro Skill > Resonance Skill",
        "materials": "**Ascension:** Truth in Lies ×46 (boss), Afterlife ×60, Polygon Cores ×32, 170k Shell.\n**Talents:** Helix ×175 (forgery), The Netherworld's Stare ×26 (weekly boss), Polygon Cores ×150, 2.03M Shell.",
        "notes": "Echo Skill DPS. Main echo Nightmare: Hecate. R1 has 57.3% base Crit Rate — prioritise Crit Rate ONLY until capped, then Crit DMG.",
        "patch": "3.3",
    },
    "Denia": {
        "role": "Main DPS",
        "element": "Fusion",
        "weapon": "Forged Dwarf Star",
        "echo_sets": ["Chromatic Foam (5pc) — Fusion Burst", "Reel of Spliced Memories (5pc) — Tune Strain"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Fusion DMG%",
            "3-cost-alt": "Fusion DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Forte Circuit ≈ Resonance Liberation > Resonance Skill > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Burning Judgment ×46 (boss), Dream of Stars ×60, Mech Cores ×32, 170k Shell.\n**Talents:** Strings ×175 (forgery), We Who Question ×26 (weekly boss), Mech Cores ×150, 2.03M Shell.",
        "notes": "Echo set is team-dependent: Chromatic Foam (Fusion Burst) or Reel of Spliced Memories (Tune Strain). Energy Regen 120–125%. Flaming Clawprint / Moonlit Clouds are alternatives.",
        "patch": "3.x",
    },
    "Yinlin": {
        "role": "Sub-DPS / Support",
        "element": "Electro",
        "weapon": "Stringmaster",
        "echo_sets": ["Void Thunder (5pc)"],
        "echo_mains": {
            "4-cost": "Electro DMG%",
            "3-cost": "ATK%",
            "3-cost-alt": "CRIT Rate",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Off-field Electro sub-DPS via coordinated attacks. Stringmaster is BiS; Cosmic Ripples is a strong alternative.",
        "patch": "1.1",
    },
    "Buling": {
        "role": "Support / Healer",
        "element": "Electro",
        "weapon": "Stellar Symphony",
        "echo_sets": ["Rejuvenating Glow (5pc)"],
        "echo_mains": {
            "4-cost": "Healing Bonus%",
            "3-cost": "Energy Regen",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["Energy Regen", "ATK%", "Flat ATK", "CRIT Rate"],
        "notes": "Top-tier 4★ healer. Weapon Stellar Symphony (Variation is a solid budget alt). Aim Energy Regen ~150%, ATK >1800.",
    },
    "Lucy": {
        "role": "Main DPS",
        "element": "Spectro",
        "weapon": "Spectral Trigger",
        "echo_sets": ["Spectro 1+2+2 Sonata mix — main echo Nightmare: Adam Smasher"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Spectro DMG%",
            "3-cost-alt": "Spectro DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Resonance Liberation > Forte Circuit > Resonance Skill > Basic Attack ≈ Intro Skill",
        "materials": "**Ascension:** Nightmare Flashdrive ×46 (boss), Past Reveries ×60, Exoswarm Cores ×32, 170k Shell.\n**Talents:** Combustor ×175 (forgery), Gold in Memory ×26 (weekly boss), Exoswarm Cores ×150, 2.03M Shell.",
        "notes": "Collab DPS — Heavy Attack & Hack DMG focused. Uses the 1+2+2 single-piece Sonata system; main echo Nightmare: Adam Smasher. Spectral Trigger is BiS.",
        "patch": "3.4",
    },
    "Rebecca": {
        "role": "Sub-DPS / Support",
        "element": "Electro",
        "weapon": "Skull Thrasher",
        "echo_sets": ["Shadow of Shattered Dreams (1pc) + Celestial Light (2pc) + Lingering Tunes (2pc)"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Electro DMG%",
            "3-cost-alt": "Electro DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Resonance Liberation ≈ Forte Circuit > Resonance Skill > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Nightmare Flashdrive ×46 (boss), Past Reveries ×60, Mech Cores ×32, 170k Shell.\n**Talents:** Combustor ×175 (forgery), We Who Question ×26 (weekly boss), Mech Cores ×150, 2.03M Shell.",
        "notes": "Collab Electro sub-DPS. Skull Thrasher gives Basic Attack DMG + team ATK buff. Main echo Adam Smasher. Energy Regen ~125%; roll Basic Attack DMG where possible.",
        "patch": "3.4",
    },
    "Zhezhi": {
        "role": "Sub-DPS / Support",
        "element": "Glacio",
        "weapon": "Rime-Draped Sprouts",
        "echo_sets": ["Freezing Frost (5pc)", "Empyrean Anthem (5pc) — sub-DPS"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Glacio DMG%",
            "3-cost-alt": "Glacio DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Resonance Skill ≈ Forte Circuit > Resonance Liberation > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Sound-Keeping Tacet Core ×46 (boss), Lanternberry ×60, Howler Cores ×32, 170k Shell.\n**Talents:** Helix ×175 (forgery), Monument Bell ×26 (weekly boss), Howler Cores ×150, 2.03M Shell.",
        "notes": "Coordinated-attack Glacio sub-DPS. Main echo Nightmare: Lampylumen Myriad. Keep a 1:2 crit ratio; one 3-cost can swap to Energy Regen if needed.",
        "patch": "1.2",
    },
    "Lupa": {
        "role": "Sub-DPS / Support",
        "element": "Fusion",
        "weapon": "Wildfire Mark",
        "echo_sets": ["Flaming Clawprint (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Fusion DMG%",
            "3-cost-alt": "Fusion DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Resonance Liberation > Forte Circuit > Intro Skill ≈ Basic Attack > Resonance Skill",
        "materials": "**Ascension:** Unfading Glory ×46 (boss), Bloodleaf Viburnum ×60, Howler Cores ×32, 170k Shell.\n**Talents:** Waveworn Residue ×175 (forgery), The Netherworld's Stare ×26 (weekly boss), Howler Cores ×150, 2.03M Shell.",
        "notes": "Fusion DPS/buffer with team-wide DMG bonus. Main echo Lioness of Glory (4-cost). Discord / Waning Redshift are budget weapons.",
        "patch": "3.1",
    },
    "Hiyuki": {
        "role": "Main DPS",
        "element": "Glacio",
        "weapon": "Frostburn",
        "echo_sets": ["Wishes of Quiet Snowfall (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Glacio DMG%",
            "3-cost-alt": "Glacio DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["Energy Regen", "CRIT DMG", "CRIT Rate", "ATK%"],
        "skill_priority": "Resonance Liberation ≈ Basic Attack > Forte Circuit > Resonance Skill > Intro Skill",
        "materials": "**Ascension:** Our Choice ×46 (boss), Redbell ×60, Exoswarm Cores ×32, 170k Shell.\n**Talents:** Polarizer ×175 (forgery), We Who Question ×26 (weekly boss), Exoswarm Cores ×150, 2.03M Shell.",
        "notes": "Glacio Chafe DPS. Main echo Reminiscence: Threnodian – Voidborne Construct. ER ~120%, crit ~70:250. Emerald of Genesis is the budget weapon.",
        "patch": "3.3",
    },
    "Aemeath": {
        "role": "Main DPS",
        "element": "Fusion",
        "weapon": "Everbright Polestar",
        "echo_sets": ["Trailblazing Star (3pc) + Molten Rift (2pc)", "Molten Rift (5pc) — budget"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Fusion DMG%",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Forte Circuit ≈ Resonance Liberation > Resonance Skill > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Our Choice ×46 (boss), Moss Amber ×60, Exoswarm Cores ×32, 170k Shell.\n**Talents:** Phlogiston ×175 (forgery), Gold in Memory ×26 (weekly boss), Exoswarm Cores ×150, 2.03M Shell.",
        "notes": "Resonance Liberation Fusion DPS. ER ~120%, keep a 1:2 crit ratio. Molten Rift is the budget set.",
        "patch": "3.1",
    },
    "Augusta": {
        "role": "Main DPS",
        "element": "Electro",
        "weapon": "Thunderflare Dominion",
        "echo_sets": ["Crown of Valor (3pc) + Void Thunder (2pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Electro DMG%",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Resonance Liberation > Forte Circuit > Basic Attack > Resonance Skill > Intro Skill",
        "materials": "**Ascension:** Blighted Crown of Puppet King ×46 (boss), Luminous Calendula ×60, Tidal Residuum ×32, 170k Shell.\n**Talents:** Waveworn Residue ×175 (forgery), When Irises Bloom ×26 (weekly boss), Tidal Residuum ×150, 2.03M Shell.",
        "notes": "ATK / Heavy-Attack Electro DPS. Aim 70–80% Crit Rate, ATK >2100, ~250% Crit DMG. Roll Heavy Attack DMG.",
        "patch": "2.6",
    },
    "Chisa": {
        "role": "Sub-DPS / Support",
        "element": "Havoc",
        "weapon": "Kumokiri",
        "echo_sets": ["Thread of Severed Fate (3pc) + Sun-sinking Eclipse (2pc)", "Rejuvenating Glow (5pc) — support"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Havoc DMG%",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Forte Circuit ≈ Resonance Liberation > Basic Attack > Resonance Skill > Intro Skill",
        "materials": "**Ascension:** Abyssal Husk ×46 (boss), Summer Flower ×60, Polygon Cores ×32, 170k Shell.\n**Talents:** Waveworn Residue ×175 (forgery), When Irises Bloom ×26 (weekly boss), Polygon Cores ×150, 2.03M Shell.",
        "notes": "Negative-status support/sub-DPS. Kumokiri BiS (Wildfire Mark alt). Thread of Severed Fate for damage, Rejuvenating Glow for a pure-support build.",
        "patch": "2.8",
    },
    "Ciaccona": {
        "role": "Sub-DPS / Support",
        "element": "Aero",
        "weapon": "Woodland Aria",
        "echo_sets": ["Gusts of Welkin (5pc)", "Moonlit Clouds (5pc) — Spectro Frazzle teams"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Aero DMG%",
            "3-cost-alt": "Aero DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Resonance Liberation > Forte Circuit > Resonance Skill > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Blazing Bone ×46 (boss), Golden Fleece ×60, Tidal Residuum ×32, 170k Shell.\n**Talents:** Cadence ×175 (forgery), The Netherworld's Stare ×26 (weekly boss), Tidal Residuum ×150, 2.03M Shell.",
        "notes": "Aero Erosion sub-DPS. Woodland Aria BiS (Phasic Homogenizer close 2nd). Moonlit Clouds when used as a buffer in Spectro Frazzle teams.",
        "patch": "3.0",
    },
    "Galbrena": {
        "role": "Main DPS",
        "element": "Fusion",
        "weapon": "Lux & Umbra",
        "echo_sets": ["Flamewing's Shadow (5pc)", "Flamewing's Shadow (3pc) + Molten Rift (2pc)"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Fusion DMG%",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Forte Circuit > Resonance Liberation > Basic Attack > Resonance Skill > Intro Skill",
        "materials": "**Ascension:** Blighted Crown of Puppet King ×46 (boss), Stone Rose ×60, Tidal Residuum ×32, 170k Shell.\n**Talents:** Phlogiston ×175 (forgery), Curse of the Abyss ×26 (weekly boss), Tidal Residuum ×150, 2.03M Shell.",
        "notes": "Echo Skill / Heavy Attack Fusion DPS. Main echo Corrosaurus (3-cost). ER ~120%. Roll Heavy Attack DMG.",
        "patch": "3.x",
    },
    "Iuno": {
        "role": "Sub-DPS / Main DPS",
        "element": "Aero",
        "weapon": "Moongazer's Sigil",
        "echo_sets": ["Crown of Valor (3pc) + Sierra Gale (2pc)"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Aero DMG%",
            "3-cost-alt": "Aero DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Forte Circuit > Resonance Liberation ≈ Resonance Skill > Basic Attack > Intro Skill",
        "materials": "**Ascension:** Abyssal Husk ×46 (boss), Sliverglow Bloom ×60, Polygon Cores ×32, 170k Shell.\n**Talents:** Cadence ×175 (forgery), The Netherworld's Stare ×26 (weekly boss), Polygon Cores ×150, 2.03M Shell.",
        "notes": "Resonance Liberation Aero sub-DPS (can hypercarry). Main echo Lady of the Sea (4-cost). ER ~120–125%; roll Res Liberation DMG.",
        "patch": "3.x",
    },
    "Lumi": {
        "role": "Support / Sub-DPS",
        "element": "Electro",
        "weapon": "Discord",
        "echo_sets": ["Moonlit Clouds (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Electro DMG%",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "Energy Regen",
        },
        "substats": ["Energy Regen", "ATK%", "CRIT Rate", "CRIT DMG"],
        "notes": "4★ Resonance-Skill buffer for quickswap teams. Moonlit Clouds + Discord enable fast rotations; buffs next unit's ATK via Outro.",
        "patch": "2.x",
    },
    "Luuk Herssen": {
        "role": "Main DPS",
        "element": "Spectro",
        "weapon": "Daybreaker's Spine",
        "echo_sets": ["Rite of Gilded Revelation (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Spectro DMG%",
            "3-cost-alt": "Spectro DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Aerial Basic-Attack Spectro DPS. Main echo Twin Nova: Nebulous Cannon (3-cost). ER ~120%; roll Basic Attack DMG. Alts: Pulsation Bracer, Abyss Surges.",
        "patch": "3.1",
    },
    "Lynae": {
        "role": "Sub-DPS / Support",
        "element": "Spectro",
        "weapon": "Spectrum Blaster",
        "echo_sets": ["Pact of Neonlight Leap (5pc)", "Moonlit Clouds (5pc) — buffer"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Spectro DMG%",
            "3-cost-alt": "Spectro DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Spectro sub-DPS/buffer. Main echo Hyvatia (team all-type buff). Spectrum Blaster BiS; ER ~120%; roll Basic Attack DMG. Static Mist if used purely as a buffer.",
        "patch": "3.2",
    },
    "Mornye": {
        "role": "Support / Healer",
        "element": "Fusion",
        "weapon": "Starfield Calibrator",
        "echo_sets": ["Halo of Starry Radiance (5pc)", "Rejuvenating Glow (5pc)"],
        "echo_mains": {
            "4-cost": "Healing Bonus%",
            "3-cost": "Energy Regen",
            "3-cost-alt": "Energy Regen",
            "1-cost": "DEF%",
            "1-cost-2": "DEF%",
        },
        "substats": ["Energy Regen", "DEF%", "Flat DEF", "CRIT DMG"],
        "notes": "DEF-scaling healer/buffer. Needs ~260% total Energy Regen to max team buffs. Discord is the budget weapon.",
        "patch": "3.0",
    },
    "Qiuyuan": {
        "role": "Sub-DPS / Support",
        "element": "Aero",
        "weapon": "Emerald Sentence",
        "echo_sets": ["Law of Harmony (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Aero DMG%",
            "3-cost-alt": "Aero DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Echo-Skill amplifier / Aero sub-DPS. ER ~130%; aim ≥65% Crit Rate; roll Heavy Attack DMG. Core to Echo-Skill teams (Sigrika, Galbrena, Phrolova, Cantarella).",
        "patch": "3.x",
    },
    "Rover (Aero)": {
        "role": "Sub-DPS / Support",
        "element": "Aero",
        "weapon": "Bloodpact's Pledge",
        "echo_sets": ["Windward Pilgrimage (5pc) — sub-DPS", "Rejuvenating Glow (5pc) — support healer"],
        "echo_mains": {
            "4-cost": "CRIT DMG",
            "3-cost": "Aero DMG%",
            "3-cost-alt": "Aero DMG%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "notes": "Aero Erosion sub-DPS / healer hybrid. Main echo Reminiscence: Fleurdelys (sub-DPS) or Fallacy of No Return (support). Best support healer in Aero Erosion teams.",
        "patch": "2.2",
    },
    "Sigrika": {
        "role": "Main DPS",
        "element": "Aero",
        "weapon": "Solsworn Ciphers",
        "echo_sets": ["Sound of True Name (5pc)"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Energy Regen",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["CRIT Rate", "CRIT DMG", "ATK%", "Energy Regen"],
        "skill_priority": "Forte Circuit > Resonance Liberation > Basic Attack ≈ Resonance Skill > Intro Skill",
        "materials": "**Ascension:** Our Choice ×46 (boss), Arithmetic Shell ×60, Exoswarm Pendants ×32, 170k Shell.\n**Talents:** Waveworn Shards ×175 (forgery), Gold in Memory ×26 (weekly boss), Exoswarm Pendants ×150, 2.03M Shell.",
        "notes": "Echo-Skill Aero DPS. Needs ~150% Energy Regen for her max Echo Skill DMG bonus. Main echo Nameless Explorer. Blazing Justice is a strong alt weapon.",
        "patch": "3.2",
    },
    "Youhu": {
        "role": "Support / Healer",
        "element": "Glacio",
        "weapon": "Abyss Surges",
        "echo_sets": ["Rejuvenating Glow (5pc)", "Freezing Frost (5pc)"],
        "echo_mains": {
            "4-cost": "Healing Bonus%",
            "3-cost": "Energy Regen",
            "3-cost-alt": "ATK%",
            "1-cost": "ATK%",
            "1-cost-2": "ATK%",
        },
        "substats": ["Energy Regen", "ATK%", "CRIT Rate", "CRIT DMG"],
        "notes": "4★ coordinated-attack support/healer. Main echo Lampylumen Myriad (or Bell-Borne Geochelone for a pure healer). Marcato is the budget weapon. Best in coordinated-attack teams.",
        "patch": "1.x",
    },
    "Yuanwu": {
        "role": "Support / Sub-DPS",
        "element": "Electro",
        "weapon": "Amity Accord",
        "echo_sets": ["Moonlit Clouds (5pc) — support", "Void Thunder (5pc) — damage"],
        "echo_mains": {
            "4-cost": "CRIT Rate",
            "3-cost": "Energy Regen",
            "3-cost-alt": "Electro DMG%",
            "1-cost": "DEF%",
            "1-cost-2": "DEF%",
        },
        "substats": ["Energy Regen", "DEF%", "CRIT Rate", "CRIT DMG"],
        "notes": "DEF-scaling defensive Electro support. Main echo Tempest Mephis. Amity Accord (DEF) BiS; Abyss Surges for more Energy Regen.",
        "patch": "1.0",
    },
}


# Character portrait images (game8 CDN, hotlinkable /show URLs) injected into
# build data via get_build(). Kept separate to keep BUILDS entries tidy.
IMAGES: dict[str, str] = {
    'Aalto': 'https://img.game8.co/3881731/791dd6376ae274a29e8794f34a93f44f.png/show',
    'Aemeath': 'https://img.game8.co/4405787/5dd70f39e199aea233791ca8d2781336.png/show',
    'Augusta': 'https://img.game8.co/4258420/5fc2426fb45527a2a5d3fd6d86641d1a.png/show',
    'Baizhi': 'https://img.game8.co/4303116/fee43219645462f11309ac6b33074947.png/show',
    'Brant': 'https://img.game8.co/4462690/7975c3a7ff99fb1fc4f01234f8405af5.png/show',
    'Buling': 'https://img.game8.co/4305268/d8caf5a1a4736d83005505f2e402caa2.png/show',
    'Calcharo': 'https://img.game8.co/3881741/8fab60225c8c4cfb01f3629b53e4f715.png/show',
    'Camellya': 'https://img.game8.co/3989202/361a1fd88afa1402b47792bb78d21acc.png/show',
    'Cantarella': 'https://img.game8.co/4112558/a621477078c614bb41f711b529fecd42.png/show',
    'Carlotta': 'https://img.game8.co/4075183/20c62a18c4469173bb2fc3520867f705.png/show',
    'Cartethyia': 'https://img.game8.co/4194024/843ce40cabed8a51e28f94c3a839e1ff.png/show',
    'Changli': 'https://img.game8.co/4463684/8f9a61c2e1e52fef6cc4432c9cfdf576.png/show',
    'Chisa': 'https://img.game8.co/4341621/9a155006b06bae145e00ba26f3b1d5ae.png/show',
    'Chixia': 'https://img.game8.co/3881734/240df32c77833288334d17f51907babf.png/show',
    'Ciaccona': 'https://img.game8.co/4303128/1656f548f03c8b83df5d5756bbcc3cc7.png/show',
    'Danjin': 'https://img.game8.co/4303096/e5818f20b97dc740b31061ed3eeddcbd.png/show',
    'Denia': 'https://img.game8.co/4503585/e0491f9e0e1a6f33ddae9fcf9ba2bbd1.png/show',
    'Encore': 'https://img.game8.co/3881743/3d9d8a8e3d55cb96b3bc71eae3a86798.png/show',
    'Galbrena': 'https://img.game8.co/4183865/0854fcbc0f69d784be2f27ca25e1bff0.png/show',
    'Hiyuki': 'https://img.game8.co/4480005/c385065e7de76f481a9f3b0b7749c1eb.png/show',
    'Iuno': 'https://img.game8.co/4281013/36f29c56ca68f5662b29d0a28ead50c5.png/show',
    'Jianxin': 'https://img.game8.co/4339438/f0603e40482b817f5e6f96e7e20a2fd1.png/show',
    'Jinhsi': 'https://img.game8.co/4303120/24763e189518dfc4e3f3aa650cacad2b.png/show',
    'Jiyan': 'https://img.game8.co/4463687/dc04478844547edc67ed5fdf782234f8.png/show',
    'Lingyang': 'https://img.game8.co/4303089/9e16af9146ba79fd821b9c7f00d44652.png/show',
    'Lucilla': 'https://img.game8.co/4532361/3590c3c0e55be62911c3b2199bdb8442.png/show',
    'Lucy': 'https://img.game8.co/4528263/050ccb046b00fe789302ecca565cf770.png/show',
    'Lumi': 'https://img.game8.co/3990210/97cc0e3dcc6f7e4e62a4c031b04262fb.png/show',
    'Lupa': 'https://img.game8.co/4167411/e7c3c324901cf5b269d59243f9e1dc57.png/show',
    'Luuk Herssen': 'https://img.game8.co/4348718/0608a0afb76009c05bba4caa5b59d6ea.png/show',
    'Lynae': 'https://img.game8.co/4373997/83b474004e479d2a3068e6ba841b4691.png/show',
    'Mornye': 'https://img.game8.co/4384957/7088f506d1bbbeeac64534f234b22644.png/show',
    'Mortefi': 'https://img.game8.co/3881736/cb6fd311d27a053c1dd8a773106523e7.png/show',
    'Phoebe': 'https://img.game8.co/4107282/6d97544929c22a067892f3b3a15db58f.png/show',
    'Phrolova': 'https://img.game8.co/4229956/919ffcc468fc752688b7690f67c31ebf.png/show',
    'Qiuyuan': 'https://img.game8.co/4183802/3e57496c7f581e32ac195219a339f9f7.png/show',
    'Rebecca': 'https://img.game8.co/4528262/b01fc2c129dd1870b50015b5f0f2eb5b.png/show',
    'Roccia': 'https://img.game8.co/4234923/5a3828ede0260465eb1568f38824c6dc.png/show',
    'Rover (Aero)': 'https://img.game8.co/4135586/e8e63936bfef45c294d3acffcb6e1a18.png/show',
    'Rover (Havoc)': 'https://img.game8.co/3881729/7e2423968428c73b30e3cf6fc7397be2.png/show',
    'Rover (Spectro)': 'https://img.game8.co/3881729/7e2423968428c73b30e3cf6fc7397be2.png/show',
    'Sanhua': 'https://img.game8.co/4303110/6d077a23694618d6d9ee885a60a2f9f2.png/show',
    'Sigrika': 'https://img.game8.co/4442463/fb582a715403f133855e7c97c781f8b0.png/show',
    'Taoqi': 'https://img.game8.co/3881737/d50c626e2bc57046404351af8e030769.png/show',
    'The Shorekeeper': 'https://img.game8.co/3945678/2dc074a2b5548ae32cd090b2ad7834b0.png/show',
    'Verina': 'https://img.game8.co/3881739/f4b5a991ff3d3130a28d7297490b16ab.png/show',
    'Xiangli Yao': 'https://img.game8.co/3930134/c527c25970e4a4b4eebe5eaf7e81c666.png/show',
    'Yangyang': 'https://img.game8.co/4303112/923df17bc1a2c9894cb85c8c8053edb3.png/show',
    'Yinlin': 'https://img.game8.co/4303122/f2572c97e3f89983fde9bd2acd504717.png/show',
    'Youhu': 'https://img.game8.co/3945677/18a980b8d2c98a751f08f5ee61ed15ed.png/show',
    'Yuanwu': 'https://img.game8.co/4303107/6b0b421e0da2416deb91ebddfe57a5ae.png/show',
    'Zani': 'https://img.game8.co/4048770/8699c1afb695a6a5c76aef58201b447c.png/show',
    'Zhezhi': 'https://img.game8.co/3930135/6b7e616a83ccad07bb7b7a30031cda0d.png/show',
}


def get_build(name: str) -> dict | None:
    b = BUILDS.get(name)
    if b is not None and "image" not in b and name in IMAGES:
        b = {**b, "image": IMAGES[name]}
    return b


def get_all_names() -> list[str]:
    return sorted(ALL_RESONATORS)
